# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e03491dee68ff79ce429dec05f2395c5f5407017fff7e51e71861cb1f9e1eb21f5820c185db354e4e0c5c903c0f37b42928ab1fcfb07204e2c605938806e411

test:
  secret_key_base: c04634a3f6c136a59f06f20f9d5f496c16ea1639f29f71e613ba43473a95be3f1c9d470acbefd334963b40d72b7301a86bc7639ebfdc5054d824f8388bf7e89d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
